name: Deploy Workflow

on:
  push:
    branches:
      - main

# env:
#   DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
#   DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Login to Docker Hub
  #     run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_ACCESS_TOKEN}}

  #   - name: Build and push Backend Docker image
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: ./tzuhsun/stylish/backend
  #       push: true
  #       tags: |
  #         tzuhsun/stylish-backend:latest
  #         tzuhsun/stylish-backend:${{ github.sha }}

  #   - name: Build and push Frontend Docker image
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: ./tzuhsun/stylish/frontend
  #       push: true
  #       tags: |
  #         tzuhsun/stylish-frontend:latest
  #         tzuhsun/stylish-frontend:${{ github.sha }}

  deploy-to-gce:
    runs-on: ubuntu-latest
    # needs: build-and-push-image
    steps:
    - name: SSH into GCE Instance and update flask server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: |
          cd /home/hsun/oop-proj-cat-collector
          git pull
          cd predict_api/app
          ps aux | grep "python3 app.py" | grep -v grep | awk '{print $2}' | xargs -r kill -9
          nohup python3 app.py &
