name: Deploy Workflow

on:
  push:
    branches:
      - main

# env:
#   DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
#   DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}

jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest
    # needs: build-and-push-image
    steps:
    - name: SSH into GCE Instance and update flask server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USERNAME }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: |
          cd /home/hsun/oop-proj-cat-collector
          git pull origin main
          cd predict_api/app
          ps aux | grep "python3 app.py" | grep -v grep | awk '{print $2}' | xargs -r kill -9
          nohup python3 app.py > /dev/null 2>&1 &
          disown
